[2023-08-26T18:11:04.534+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-26T18:10:00+00:00 [queued]>
[2023-08-26T18:11:04.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-26T18:10:00+00:00 [queued]>
[2023-08-26T18:11:04.551+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-26T18:11:04.580+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): etl_user> on 2023-08-26 18:10:00+00:00
[2023-08-26T18:11:04.590+0000] {standard_task_runner.py:57} INFO - Started process 324974 to run task
[2023-08-26T18:11:04.602+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gaas_etl_1', 'etl_user', 'scheduled__2023-08-26T18:10:00+00:00', '--job-id', '2542', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpp6_5919k']
[2023-08-26T18:11:04.617+0000] {standard_task_runner.py:85} INFO - Job 2542: Subtask etl_user
[2023-08-26T18:11:04.853+0000] {task_command.py:415} INFO - Running <TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-26T18:10:00+00:00 [running]> on host data-system.us-central1-a.c.data-system-392010.internal
[2023-08-26T18:11:05.464+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hungnm15012002@gmail.com' AIRFLOW_CTX_DAG_OWNER='hungnm' AIRFLOW_CTX_DAG_ID='gaas_etl_1' AIRFLOW_CTX_TASK_ID='etl_user' AIRFLOW_CTX_EXECUTION_DATE='2023-08-26T18:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-26T18:10:00+00:00'
[2023-08-26T18:11:05.484+0000] {dag_etl.py:28} INFO - Extracting user...
[2023-08-26T18:11:16.626+0000] {extract.py:36} INFO - Request time: 0:00:11.141954
[2023-08-26T18:11:18.182+0000] {extract.py:42} INFO - Create DataFrame time: 0:00:01.554897
[2023-08-26T18:11:18.194+0000] {dag_etl.py:31} INFO - Complete extract user: 0:00:12.709939
[2023-08-26T18:11:18.195+0000] {dag_etl.py:33} INFO - Extracting resource...
[2023-08-26T18:11:18.489+0000] {extract.py:36} INFO - Request time: 0:00:00.293212
[2023-08-26T18:11:18.489+0000] {extract.py:45} ERROR - Server GAAS error: 502
[2023-08-26T18:11:18.502+0000] {dag_etl.py:36} INFO - Complete extract resource: 0:00:00.308191
[2023-08-26T18:11:18.503+0000] {dag_etl.py:38} INFO - Transforming user...
[2023-08-26T18:11:18.508+0000] {dag_etl.py:107} ERROR - An Error Occur: Can only merge Series or DataFrame objects, a <class 'int'> was passed
[2023-08-26T18:11:18.566+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-26T18:11:18.586+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=gaas_etl_1, task_id=etl_user, execution_date=20230826T181000, start_date=20230826T181104, end_date=20230826T181118
[2023-08-26T18:11:18.653+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-26T18:11:18.684+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
